[project]
name = "api-trafix"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "nzsnyn", email = "672023013@student.uksw.edu" }
]
requires-python = ">=3.13"
dependencies = [
    "aiomqtt>=2.3.0",
    "alembic>=1.19.0",
    "asyncpg>=0.31.0",
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "openpyxl>=3.1.5",
    "pydantic-settings>=2.14.2",
    "pydantic[email]>=2.13.4",
    "pyjwt>=2.13.0",
    "python-dotenv>=1.2.2",
    "python-multipart>=0.0.32",
    "redis[hiredis]>=8.1.0",
    "reportlab>=5.0.1",
    "sqlalchemy[asyncio]>=2.0.51",
    "uvicorn>=0.52.1",
    "werkzeug>=3.1.8",
]

[project.scripts]
api-trafix = "api_trafix:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "amqtt>=0.11.0",
    "pytest>=8.0.0",
    "pytest-asyncio>=0.24.0",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]

